<?php

namespace Adition\AdBundle\Repository;

use Adition\AdBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Adition\AdBundle\Entity\Banner;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{

    public function create(User $user, $params)
    {
        $banner = new Banner();
        $banner->setName($params['name']);
        $banner->setCaption($params['caption']);
        $banner->setUrl($params['url']);
        $banner->setExtension($params['extension']);
        $banner->setHeight($params['height']);
        $banner->setWidth($params['width']);
        $banner->setUser($user);
        $this->_em->persist($banner);
        $this->_em->flush();
    }
}
