<?php

namespace Adition\AdBundle\Repository;

use DateTime;
use Adition\AdBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Adition\AdBundle\Entity\Campaign;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends EntityRepository
{

    /**
     * @param User $user
     * @param $params
     * @return Campaign
     */
    public function create(User $user, $params)
    {
        $campaign = new Campaign();
        $campaign->setName($params['name']);
        $campaign->setUser($user);
        $campaign->setRequestLimit((int)$params['requestLimit']);
        $campaign->setStartDate(new DateTime($params['startDate']));
        $campaign->setEndDate(new DateTime($params['endDate']));
        $campaign->setState((int)$params['state']);
        $this->_em->persist($campaign);
        $this->_em->flush();

        return $campaign;

    }

    /**
     * @param User $user
     * @param $params
     * @param $id
     * @return Campaign|null
     */
    public function update(User $user, $params, $id)
    {
        $campaign = $this->findOneBy(['user' => $user, 'id' => $id]);
        if ($campaign) {
            $campaign->setName($params['name']);
            $campaign->setRequestLimit((int)$params['requestLimit']);
            $campaign->setStartDate(new DateTime($params['startDate']));
            $campaign->setEndDate(new DateTime($params['endDate']));
            $campaign->setState((bool)$params['state']);
            $this->_em->persist($campaign);
            $this->_em->flush();

            return $campaign;
        }
    }

    /**
     * @param $user
     * @param $id
     */
    public function delete($user, $id)
    {
        $campaign = $this->findOneBy(['user' => $user, 'id' => $id]);
        if ($campaign) {
            $this->_em->remove($campaign);
        }

    }

    /**
     * @param $data
     */
    public function addBannerToCampaign($data)
    {
        /** @var Campaign $campaign */
        $campaign = $data['campaign'];
        $campaign->addBanner($data['banner']);
        $campaign->setBannerCount($campaign->getBannerCount() + 1);
        $this->_em->persist($campaign);

        $this->_em->flush();
    }
}
