<?php

namespace Adition\AdBundle\Repository;

use Adition\AdBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Adition\AdBundle\Entity\ContentUnit;

/**
 * ContentUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentUnitRepository extends EntityRepository
{

    /**
     * @param $data
     * @param User $user
     * @return ContentUnit
     */
    public function create($data, User $user)
    {
        $contentUnit = new ContentUnit();
        $contentUnit->setHeight($data['height']);
        $contentUnit->setWidth($data['width']);
        $contentUnit->setUser($user);
        $this->_em->persist($contentUnit);
        $this->_em->flush();

        return $contentUnit;
    }

    /**
     * @param $data
     * @param User $user
     * @return bool
     */
    public function alreadyExists($data, User $user)
    {
        $contentUnit = $this->findOneBy([
            'user' => $user,
            'height' => $data['height'],
            'width' => $data['width']
        ]);

        if (!$contentUnit) {
            return false;
        }

        return true;
    }

    /**
     * @param $id
     * @param User $user
     * @return bool
     */
    public function delete($id, User $user)
    {
        $contentUnit = $this->findOneBy(['id' => $id, 'user' => $user]);
        if ($contentUnit) {
            $this->_em->remove($contentUnit);

            return true;
        }

        return false;
    }
}
